#!/usr/bin/python

import os
import commands

alarmes = "/home/henrique/.alarmes"
ico = "/home/henrique/.clock.png"
sound = "/home/henrique/.alarme.mp3"
hora = commands.getoutput("date +'%H:%M'")

def main():
    notifica()
    print(prox_alarme(hora))

def prox_alarme(hora):
    arquivo = open(alarmes)
    arquivo = arquivo.readlines()
    if len(arquivo) > 0:
        arquivo.sort()
        for alarme in arquivo:
            if alarme[:-1] >= hora:
                return alarme[:-1]
        return arquivo[0][:-1]
    else:
        return '' 

def rm_alarme(hora):
    alarme = open(alarmes)
    alarme = alarme.readlines()
    alarme.remove("%s\n"%hora)
    alarme.sort()
    arquivo = open(alarmes, "w")
    for i in alarme:
        arquivo.write(i)
    arquivo.close()

def notifica():
    if hora == prox_alarme(hora):
        os.system("notify-send -i %s Alarme: %s"%(ico, hora))
        os.system("mpg123 %s"%sound)
        rm_alarme(prox_alarme(hora))

main()
