#!/usr/bin/env python

import commands as c
import time

icon = '~/.icons/Arc/apps/24@2x/gnome-power-manager.png'

while True:
    porcentagem = c.getoutput('acpi')
    porcentagem = int(porcentagem[porcentagem.find(",")+2:porcentagem.find("%")])

    if 'Charging' in c.getoutput('acpi') and porcentagem == 100:
        c.getoutput("notify-send -i %s 'Battery Full\n%s%% remaining'"%(icon, porcentagem))
        time.sleep(300)
        continue
    elif 'Unknown' in c.getoutput('acpi'):
        continue
    else:
        if porcentagem == 10:
            c.getoutput("notify-send -i %s 'Low Battery\n%s%% remaining'"%(icon, porcentagem))
            time.sleep(180)
            continue
        elif porcentagem == 5:
            c.getoutput("notify-send -i %s -u critical 'Low Battery\n%s%% remaining'"%(icon, porcentagem))
            time.sleep(180)
            continue
