#!/usr/bin/env python3
import json
import urllib.request

CURRENCY = "BRL"
with urllib.request.urlopen("https://blockchain.info/ticker") as url:
    data = json.loads(url.read().decode())
    valor = data[CURRENCY]['last']
    valor = str(valor)
    valor = valor[:2] + '.' + valor[2:5]
    print ("BTC", valor)
