#!/bin/bash
res=$(echo -e "Shutdown\nReboot\ni3lock\nExit" | dmenu -i -p "Power:")

if [ ! -z $res ]; then
	case $res in
		Shutdown)
			confirma=$(echo -e "Yes\nNo" | dmenu -i -p "Confirm:")
				[ $confirma = "Yes" ] && systemctl poweroff
		;;
		Reboot)
			confirma=$(echo -e "Yes\nNo" | dmenu -i -p "Confirm:")
			[ $confirma = "Yes" ] && systemctl reboot
		;;
		i3lock)
			i3lock --color 090909
		;;
	    Exit)
			confirma=$(echo -e "Yes\nNo" | dmenu -i -p "Confirm:")
			[ $confirma = "Yes" ] && i3-msg exit
		;;
		*)
		;;
	esac
fi
