#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

TOGGLE=$HOME/.toggle

if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    ~/.config/i3/scripts/screencaster.sh &
else
    rm $TOGGLE
    ~/.config/i3/scripts/screencaster.sh &
fi
