#!/usr/bin/python

import commands
import calendar

date = commands.getoutput("date +%m/%Y")

calendario = commands.getoutput("echo '%s' | rofi -width 17 -lines 7 -hide-scrollbar -separator-style none -xoffset 355 -yoffset -262 -dmenu -p Calendar"%calendar.month(int(date[3:]), int(date[:2])))

while calendario != '':
    calendario = commands.getoutput("echo '%s' | rofi -width 17 -lines 7 -hide-scrollbar -separator-style none -xoffset 355 -yoffset -262 -dmenu -p Calendar"%calendar.month(int(calendario[3:]), int(calendario[:2])))


